//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WEBAPI_Server_App.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OrderApplicationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OrderApplicationEntities object using the connection string found in the 'OrderApplicationEntities' section of the application configuration file.
        /// </summary>
        public OrderApplicationEntities() : base("name=OrderApplicationEntities", "OrderApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrderApplicationEntities object.
        /// </summary>
        public OrderApplicationEntities(string connectionString) : base(connectionString, "OrderApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrderApplicationEntities object.
        /// </summary>
        public OrderApplicationEntities(EntityConnection connection) : base(connection, "OrderApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderApplicationModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        /// <param name="orderedItem">Initial value of the OrderedItem property.</param>
        /// <param name="orderedQuantity">Initial value of the OrderedQuantity property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        /// <param name="totalBill">Initial value of the TotalBill property.</param>
        public static Order CreateOrder(global::System.Int32 orderId, global::System.String customerName, global::System.String orderedItem, global::System.Int32 orderedQuantity, global::System.Int32 unitPrice, global::System.Int32 totalBill)
        {
            Order order = new Order();
            order.OrderId = orderId;
            order.CustomerName = customerName;
            order.OrderedItem = orderedItem;
            order.OrderedQuantity = orderedQuantity;
            order.UnitPrice = unitPrice;
            order.TotalBill = totalBill;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderedItem
        {
            get
            {
                return _OrderedItem;
            }
            set
            {
                OnOrderedItemChanging(value);
                ReportPropertyChanging("OrderedItem");
                _OrderedItem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderedItem");
                OnOrderedItemChanged();
            }
        }
        private global::System.String _OrderedItem;
        partial void OnOrderedItemChanging(global::System.String value);
        partial void OnOrderedItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderedQuantity
        {
            get
            {
                return _OrderedQuantity;
            }
            set
            {
                OnOrderedQuantityChanging(value);
                ReportPropertyChanging("OrderedQuantity");
                _OrderedQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderedQuantity");
                OnOrderedQuantityChanged();
            }
        }
        private global::System.Int32 _OrderedQuantity;
        partial void OnOrderedQuantityChanging(global::System.Int32 value);
        partial void OnOrderedQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Int32 _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Int32 value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalBill
        {
            get
            {
                return _TotalBill;
            }
            set
            {
                OnTotalBillChanging(value);
                ReportPropertyChanging("TotalBill");
                _TotalBill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalBill");
                OnTotalBillChanged();
            }
        }
        private global::System.Int32 _TotalBill;
        partial void OnTotalBillChanging(global::System.Int32 value);
        partial void OnTotalBillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderedDate
        {
            get
            {
                return _OrderedDate;
            }
            set
            {
                OnOrderedDateChanging(value);
                ReportPropertyChanging("OrderedDate");
                _OrderedDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderedDate");
                OnOrderedDateChanged();
            }
        }
        private global::System.String _OrderedDate;
        partial void OnOrderedDateChanging(global::System.String value);
        partial void OnOrderedDateChanged();

        #endregion

    
    }

    #endregion

    
}
